#include <string>
#include <fstream>
#include <windows.h>
#include <wincrypt.h>
#include "Structures.h"
#include <vector>
#include <iomanip>
#include <string_view>
#include <type_traits>
#include <cstdlib>
#include <algorithm>
#include <iostream>
#include <sstream>
#include <array>
#include <random>
#include <functional>
